# -*- coding: utf-8 -*-
"""TASK2(2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uQZEVUC21mI_D4vrkQIQdDvcShxQcwaJ
"""

import pandas as pd

df = pd.read_csv('/content/01.Data Cleaning and Preprocessing.csv')

df.info()

head = df.head()
head

type(df)

df.describe()

df.drop_duplicates()
df

df.isnull()

df.isnull().sum()

df.isnull().sum().sum()

df1 = df.fillna(value=0)
df1

df2 = df.fillna(method = 'pad')
df2

import numpy as np
from scipy import stats

# Detect Outlier using IQR
df2.columns

df2.drop(['Observation'], axis=1, inplace=True)
df2.columns

Q1 = df2.quantile(0.25)
Q3 = df2.quantile(0.75)
IQR = Q3 - Q1
print(IQR)

df2 = df2[~((df2 < (Q1 - 1.5 * IQR)) |(df2 > (Q3 + 1.5 * IQR))).any(axis=1)]
df2.shape
df2

df1.describe()