# -*- coding: utf-8 -*-
"""Mainflow_Internship.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AtDHP3mYCFZsXL362d8qSFT5um0tgk15
"""

# Basic Operations with List
print("List operations :")
list1 = ['banana', 2, True, '34']
print(list1)
# Adding an element to the list
list1.append(100)
print("List with added element : ",list1)
# Removing an element from the list
list1.remove(True)
print("List with removed element : ",list1)
# modify list element
list1[2] = "black"
print("Modified list : ",list1)

# Basic Operations With Dictionary
print("Dictionary operations : ")
dic1 = {1 : "a", 2 : "b", 3 : "c", 4 : "d"}
print(dic1)
# Adding an element to the dictionary
dic1[5] = "e"
print("Dictionary with added element : ",dic1)
# Removing an element from the dictionary
del(dic1[5])
print("Dictionary with removed element : ",dic1)
# Modify dectionary element
dic1[4] = "web"
print("Modified dictionary : ",dic1)

# Basic Operations With Set
print("Set operations : ")
set1 = {1,2,3,4,5}
print(set1)
# Adding an element to the set
set1.add(6)
print("List with added element : ",set1)
# Removing an element from the set
set1.remove(6)
print("List with removed element : ",set1)