# -*- coding: utf-8 -*-
"""Task3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C5pPOPD2JwBbI0bEKj7Hi5d_G1Q5W3Lg
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/INDIAvi.csv')

df.head()

df.info()

df = df.dropna(subset=['views', 'likes', 'dislikes', 'comment_count'])

plt.figure(figsize=(12, 6))
plt.plot(df.index, df['views'], color='blue', label='Views')
plt.plot(df.index, df['likes'], color='green', label='Likes')
plt.plot(df.index, df['dislikes'], color='red', label='Dislikes')
plt.plot(df.index, df['comment_count'], color='purple', label='Comment Count')
plt.title('Line Chart for Views, Likes, Dislikes, and Comment Count', fontsize=16)
plt.xlabel('Index', fontsize=12)
plt.ylabel('Count', fontsize=12)
plt.legend()
plt.grid(True)
plt.show()

df_bar = df.head(20)
fig, axes = plt.subplots(2, 2, figsize=(12, 10))
df_bar.plot(kind='bar', x='video_id', y='views', ax=axes[0, 0], color='blue', legend=False)
axes[0, 0].set_title('Views')
axes[0, 0].set_ylabel('Views Count')
axes[0, 0].tick_params(axis='x', rotation=90)

df_bar.plot(kind='bar', x='video_id', y='likes', ax=axes[0, 1], color='green', legend=False)
axes[0, 1].set_title('Likes')
axes[0, 1].set_ylabel('Likes Count')
axes[0, 1].tick_params(axis='x', rotation=90)

df_bar.plot(kind='bar', x='video_id', y='dislikes', ax=axes[1, 0], color='red', legend=False)
axes[1, 0].set_title('Dislikes')
axes[1, 0].set_ylabel('Dislikes Count')
axes[1, 0].tick_params(axis='x', rotation=90)

df_bar.plot(kind='bar', x='video_id', y='comment_count', ax=axes[1, 1], color='purple', legend=False)
axes[1, 1].set_title('Comment Count')
axes[1, 1].set_ylabel('Comment Count')
axes[1, 1].tick_params(axis='x', rotation=90)

plt.tight_layout()
plt.show()

df_bar = df.head(20)
df_bar[['views', 'likes', 'dislikes', 'comment_count']].plot(
    kind='bar', stacked=True, figsize=(12, 6), color=['blue', 'green', 'red', 'purple'])
plt.title('Stacked Bar Chart for Views, Likes, Dislikes, and Comment Count (Top 20)', fontsize=16)
plt.xlabel('Video Index', fontsize=12)
plt.ylabel('Count', fontsize=12)
plt.xticks(ticks=range(len(df_bar)), labels=df_bar['video_id'], rotation=90)
plt.legend(['Views', 'Likes', 'Dislikes', 'Comment Count'])
plt.tight_layout()
plt.show()